### PR TITLE
Responsive Home Page

### PR DESCRIPTION
**Pull request by mpa-mxiang**
For this PR, I did those based on the fix issue PR#53:
- Fixed the scrolling issue for mobile
- Followed the Figma design to change the desktop view
- Removed the user logo from the home header for the desktop view

---------------------------------------------------------------------

UPDATE:

After the discussion with @Ant-Shell on Slack and the Jira ticket update, I made the changes:

- welcomeNavbar styles are all commented so there is no need to worry about the overlaps
- Changed the background colour to #mvp-cream to match the Figma design
- Add route for "find connection" button
- Moved two home sections lower to match the Figma design
- Removed the profile route from the user image
- Since I see there is no scroll issue for Pixel 7, I didn't make any change for that, please kindly advise me if you still see the issue with this most recent version

### CODE REVIEW

**Comment by Yvv1214** [comment]
PR 56 fixes styling errors and its good to go,
But i never accepted a PR before and am wondering what u guys think about the landing Page differences (even though we're not going use it) from the current app and PR 56 version. (The current one is the shorter vid.) not sure if we're completely booting that page or saving it for the future.

https://github.com/makeitMVPadmin/CoffeeChat/assets/39809411/0cac299a-cc97-45d3-aa8d-edeaffd67a07


https://github.com/makeitMVPadmin/CoffeeChat/assets/39809411/fdb02556-332b-49fd-8242-b31e53222fdf

**Comment by Ant-Shell** [comment]
> PR 56 fixes styling errors and its good to go, But i never accepted a PR before and am wondering what u guys think about the landing Page differences (even though we're not going use it) from the current app and PR 56 version. (The current one is the shorter vid.) not sure if we're completely booting that page or saving it for the future.
> 
>  currentWelcomePage.mp4 
>  PR.56.mp4

If we have time to review code from a past PR and reinstate it, I think the navbar from your first video clip of the Landing Page navbar looks perfectly fine. As long as the SCSS for it isn't affecting the styling in other parts of the app like it was before, or if we could correct it, it would be nice to have - even though we won't be presenting it during this iteration.

However, it might be in our best interest to leave it for a future iteration at this point. Certainly open to discussing.

**Update:** The commented code for the `<Header />` styling in `LandingPage.jsx` is still in our `develop` branch. It's in located in `WelcoomNavBar.css`. This was the code that was affecting the styling of other components. Unsure if we have time to try and fix it at this point.

**Comment by Ant-Shell** [comment]
Not ready for approval yet. Details have been provided in Slack conversation.

**Comment by mpa-mxiang** [comment]
Hi @Ant-Shell ,

Please see the UPDATE from the PR description and see if I miss anything, thank you!

**Comment by Ant-Shell** [comment]
I made some minor adjustments to this PR that did the following:
- Updated the background image used for `.home` in `HomePage.scss to `/.home-desktop.svg`
  - This allows for the updated background color to show up
- Adjusted a few properties for the background for better visibility (Mobile view)
- Updated the `.svg` code for `/.home-desktop.svg`

I have attached the result for review, but would recommend pulling this branch down into a new branch created from `develop` and verifying locally before approving. Please reach out with any questions or concerns.

Proposed updates

**Review by katiyelae — APPROVED** [review]

**Pull request merged**
