### PR TITLE
Ccl2 116 data directory

### PR DESCRIPTION
**Pull request by Ant-Shell**
**Summary**
This PR adds: 
- A directory for dummy data 
- An initial data file
-  Update to App
- Numerous user images from our [Hi-Fi Figma design](https://www.figma.com/file/gHUUMQk3YHTeyPW8gEtPZ4/Phase-2-Designs?type=design&node-id=808-3214&mode=design&t=sNbXaHPVCLyuBUxQ-0)

**Updates**
- `src/data/`
- `src/data/connectionsData.jsx`
- `src/App.js`
- `src/assets/images/DrewYoung.svg`
- `src/assets/images/JenRubio.svg`
- `src/assets/images/JordanWell.svg`
- `src/assets/images/MannyWell.svg`
- `src/assets/images/MartinJames.svg`
- `src/assets/images/RajDev.svg`
- `src/assets/images/TiffanyCrew.svg`

**Testing Instructions**
- No visual updates were made to the Frontend 
- `.svg` images were verified before submitting this PR, but can be tested locally
  - Swap out an existing image for one or more of the files to verify

### CODE REVIEW

**Comment by mpa-mxiang** [comment]
I am wondering which page I can expect to see those dummy data, could you please refer me? Thank you!

**Comment by Ant-Shell** [comment]
Hello @mpa-mxiang,  

When looking at `App.js` lines 74 and 84,  `connectionsData` is currently being passed into the `<ConnectionsPage />` and `<SchedulingPage />` components as props. `connectionsData` is being imported on line 22 of `App.js`.

Migrating the dummy data from lines 45 - 76 of `App.js` into it's own file (`src/data/connectionsData.jsx`) was one of the main focuses of this PR.

Creating a directory (`src/data/`) for us to hold additional dummy data files for various additional use cases was another focus of this PR.

Please let me know if additional clarification is needed.

**Comment by katiyelae** [comment]
Anthony, this looks great! Glad we're able to get this started and looking forward to the data for the chat page!

I am curious, the images in the connectionsData file, where can we find those? I notice you added some new ones, but am unsure where to find the images that already exist on this page

**Review by katiyelae — APPROVED** [review]

**Comment by Ant-Shell** [comment]
@katiyelae Thanks for reviewing.

The images that are in that connectionsData file don't exist. That's why I wanted to add the new placeholder images to this PR. 

We can now each create separate dummy data files for the use cases we're individually working on, and add the images from our Figma design to them. 

By creating our own separate dummy data files, we can hopefully cut back on merge conflicts.

**Pull request merged**
