### PR TITLE
Add Scheduling Page & Confirmation Page

### PR DESCRIPTION
**Pull request by quindipc**
### Summary
This code adds the scheduling page & confirmation modal component skeleton.

### Updates:
image
image
image

### Testing Instructions
In the deploy branch, run git pull in your terminal to retrieve all updates, then switch to feature branch with git checkout l70-fe-scheduling.
Start the dev environment with npm start
In your browser, view the build of the lo-fi mockup.

### CODE REVIEW

**Comment by codecaviette** [comment]
@quindipc , based on your testing instructions, i'm not clear on how to access your feature. i tried clicking on Connections in the nav bar, then clicking on a person's name, then clicking teh Connect button, but it is unresponsive. please let me know if i should be taking alternative steps to test this feature. thank you!

**Comment by quindipc** [comment]
> @quindipc , based on your testing instructions, i'm not clear on how to access your feature. i tried clicking on Connections in the nav bar, then clicking on a person's name, then clicking teh Connect button, but it is unresponsive. please let me know if i should be taking alternative steps to test this feature. thank you!

You can test it by going to http://localhost:3000/scheduling/1 -- I created a scheduling route that links to the user ID, let me now if this works @codecaviette

**Comment by quindipc** [comment]
### UPDATES:
I added a link to scheduling a meeting with a connection. 

image


### TESTING: 
Click on Connections in navbar (http://localhost:3000/)  > Click on name of person/connection (http://localhost:3000/connections) > Click on Schedule a meeting (http://localhost:3000/chat/:id) > Scheduling page will appear (http://localhost:3000/scheduling/:id)

**Review by codecaviette — APPROVED** [review]
Works as expected-- nice work!

**Pull request merged**
